# coding: utf-8

"""
    Task Manager API

    A simple task management API used to end-to-end test MCP generation (spec parse, tools, mock server, contract testing, code analysis).

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from probestack_sdk.models.add_task_comment_request import AddTaskCommentRequest

class TestAddTaskCommentRequest(unittest.TestCase):
    """AddTaskCommentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddTaskCommentRequest:
        """Test AddTaskCommentRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddTaskCommentRequest`
        """
        model = AddTaskCommentRequest()
        if include_optional:
            return AddTaskCommentRequest(
                message = '',
                author = '',
                tags = [
                    ''
                    ]
            )
        else:
            return AddTaskCommentRequest(
                message = '',
                author = '',
        )
        """

    def testAddTaskCommentRequest(self):
        """Test AddTaskCommentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
