# coding: utf-8

"""
    Task Manager API

    A simple task management API used to end-to-end test MCP generation (spec parse, tools, mock server, contract testing, code analysis).

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from probestack_sdk.models.update_task_request import UpdateTaskRequest

class TestUpdateTaskRequest(unittest.TestCase):
    """UpdateTaskRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTaskRequest:
        """Test UpdateTaskRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTaskRequest`
        """
        model = UpdateTaskRequest()
        if include_optional:
            return UpdateTaskRequest(
                title = '',
                status = 'OPEN',
                priority = 'LOW',
                completed = True
            )
        else:
            return UpdateTaskRequest(
                status = 'OPEN',
        )
        """

    def testUpdateTaskRequest(self):
        """Test UpdateTaskRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
