# coding: utf-8

"""
    Task Manager API

    A simple task management API used to end-to-end test MCP generation (spec parse, tools, mock server, contract testing, code analysis).

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from probestack_sdk.models.create_task_request import CreateTaskRequest

class TestCreateTaskRequest(unittest.TestCase):
    """CreateTaskRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTaskRequest:
        """Test CreateTaskRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTaskRequest`
        """
        model = CreateTaskRequest()
        if include_optional:
            return CreateTaskRequest(
                title = '',
                description = '',
                assignee = '',
                priority = 'LOW',
                due_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return CreateTaskRequest(
                title = '',
        )
        """

    def testCreateTaskRequest(self):
        """Test CreateTaskRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
